services:
  - type: web
    name: task-manager-backend
    env: node
    region: oregon
    plan: free
    branch: master
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
